twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
       myName: 'ahmad'
   #  form_themes:
      # [ bootstrap_4_layout.html.twig]
      #  ['fields.html.twig']
knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: nav.html.twig
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig
